### ISSUE TITLE
Look into embedding a PayPal button

### ISSUE THREAD

**Issue by D33DAA** [D33DAA/d33daa.github.io#4]
Aiden suggests I could find a PayPal button to embed somewhere which would link to my paypal. This would be handy to use.

**Comment by Rhundas** [comment]
Unnecessary as you only anticipate payment on completion of a sprite, not before you undertake the project. Your PayPal should be given to the client as a link along with a finished proof (watermarked) image of the sprite.

**Comment by D33DAA** [comment]
A valid point. I will have to look into watermarking as I had not previously considered it.

**Comment by Rhundas** [comment]
> I will have to look into watermarking as I had not previously considered it.

Opened #8
