### ISSUE TITLE
Move the Scroll to Top

### ISSUE THREAD

**Issue by D33DAA** [D33DAA/d33daa.github.io#6]
Scroll to top button blocks text when it appears. Find a better place to put it

**Comment by Rhundas** [comment]
Move it to the right side and turn the button into an arrow pointing upwards with "TOP" written in it, lad.

![](https://i.gyazo.com/082d3fdcbfdb1e63f63ddb88f70b759e.png)

**Comment by D33DAA** [comment]
A good idea. I'll check Font-Awesome for the arrow
